### PR TITLE
Better Time Variable Names

### PR DESCRIPTION
**Pull request by Si1ver**
Also fixed compilation error introduced in #26

### CODE REVIEW

**Review by chernikovdmitry — APPROVED** [review]
Holy piece of healing elixyr!
